Miha bugfix deserializer kwargs
merantix-momentum/squirrel-core pull request #102
Opened 2022-11-09 13:35 UTC by mg515

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-11-09 13:43 UTC, AlirezaSohofi reviewed
`loader_kwargs` should be added to `get_iter()` and be passed here

2022-11-09 13:43 UTC, AlirezaSohofi commented on squirrel/serialization/jsonl.py
> +        fp: str, fs: t.Optional[AbstractFileSystem] = None, mode: str = "rb", open_kwargs: t.Optional[t.Dict] = None,
```suggestion
        fp: str, fs: t.Optional[AbstractFileSystem] = None, mode: str = "rb", loader_kwargs: dict[str, Any] | None = None, **open_kwargs
```

2022-11-10 14:37 UTC, mg515 commented on squirrel/driver/jsonl.py
> -        get_kwargs: t.Optional[t.Dict] = None,
@AlirezaSohofi No more explicit `get_kwargs`, now one either needs to pass `open_kwargs`, `loader_kwargs` or `unpacker_kwargs` to `get_iter(**kwargs)`. How's that from the UX perspective?

2022-11-11 16:59 UTC, pzdkn commented on squirrel/driver/jsonl.py
> -        get_kwargs: t.Optional[t.Dict] = None,
I also think it's better to be more explicit. Will we introduce breaking changes by including`open_kwargs` and `loader_kwargs` in `MapDriver.get_iter()` and e.g `JsonDriver` though? I don't think so actually.

2023-01-23 11:36 UTC, mg515 commented on squirrel/driver/jsonl.py
> -        get_kwargs: t.Optional[t.Dict] = None,
@AlirezaSohofi @pzdkn Apologies for delay on this one. I've adapted the solution to your proposal, as now the `loader_kwargs` are added explicitly to the high level `get_iter()` API and then passed onwards to the `.get()` method. 

The only consideration from my side atm, is that we only expose `loader_kwargs`, even though they are later on used in `Unpacker` (msgpack context) as  well as `.load()` (jsonl context).
We could either find an alternative name that fits both use cases, or expose both kwargs separately (`unpacker_kwargs` as well as `loader_kwargs`). This to me feels a bit overboard. I felt that `loader_kwargs` is a suiting name for both contexts, but please let me know if you have a better idea.

2023-02-02 10:59 UTC, pzdkn requested changes
Thanks Miha, looks great. Just need some documentation updates.

2023-02-02 10:59 UTC, pzdkn commented on squirrel/driver/driver.py
> +        loader_kwargs: dict | None = None,
Can you update the doc string with loader_kwargs pls ?

2023-02-02 10:59 UTC, pzdkn commented on squirrel/driver/jsonl.py
> +                as `loader_kwargs` to :py:meth:`MapDriver.get_iter`.
might be more clear to say that it gets passed to `jsonl.load` directly

2023-03-12 18:27 UTC, closed without merging