Support running all tests in python3.7
merantix-momentum/squirrel-core pull request #105
Opened 2023-01-17 13:59 UTC by winfried-ripken

# Description

I checked for compatibility with python 3.7 - all the code runs ok, but still some tests failed. I fixed some minor issues s.t. all tests run successfully in py3.9 now.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2023-01-17 14:06 UTC, AlirezaSohofi requested changes

2023-01-17 14:06 UTC, AlirezaSohofi commented on test/test_driver/test_msgpack.py
> -    with tempfile.TemporaryDirectory() as tmp_dir:
Is this test causing issue wrt python version? 
It's generally better to use context manager for these cases. Best would be to use a fixture (see [example](https://github.com/merantix-momentum/squirrel-core/blob/main/test/conftest.py#L159)).

2023-01-17 16:03 UTC, winfried-ripken commented on test/test_driver/test_msgpack.py
> -    with tempfile.TemporaryDirectory() as tmp_dir:
yes, the problem is that the directory is already cleaned up by squirrel as expected - this is case is however not checked for in python v37 within the tempfile.TemporaryDirectory() context and therefore the test fails with an exception. Happy to discuss alternatives or leave it as is - this would mean that tests fail on py37 but the core functionality should still work ok

2023-01-18 09:18 UTC, AlirezaSohofi approved these changes

2023-01-18 09:18 UTC, AlirezaSohofi commented on test/test_driver/test_msgpack.py
> -    with tempfile.TemporaryDirectory() as tmp_dir:
:+1:

2023-01-18 12:53 UTC, merged