update requirements
merantix-momentum/squirrel-core pull request #110
Opened 2023-01-30 13:28 UTC by AlirezaSohofi

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [x] Other (please describe): update requirements

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All dependency changes have been reflected in the pip requirement files.

2023-01-30 13:33 UTC, winfried-ripken requested changes
Thanks for taking this on!
I think at some point we opted for omitting versions in the requirements.in files to keep the backwards compatibility with previous python versions - following the argument that users would be responsible themselves for installed dependencies, but still be able to use squirrel.
In that case we would just update the requirements.txt file. Wdyt?

2023-01-30 13:33 UTC, winfried-ripken commented on requirements.in
> +# older versions are insecure
Do these versions require a specific python version? Can we leave them out in this case and just update the requirements.txt file?

2023-01-30 15:48 UTC, AlirezaSohofi commented on requirements.in
> +# older versions are insecure
Not sure about the python version. These packages introduce vulnerabilities (some of them high or critical vulnerabilities), so I think we should update even if it means temporary or permanent incompatibility for older python versions.

I tried freezing the requirements without explicitly specifying minimum version but that does not solve the issue.

2023-01-31 15:24 UTC, winfried-ripken approved these changes

2023-01-31 15:37 UTC, merged