Add counter to _LoopIterable
merantix-momentum/squirrel-core pull request #139
Opened 2023-08-16 09:56 UTC by MaxSchambach

# Description

Tiny extension to add a counter to loop iterables holding the current number of iterations of an iterable.
This can be useful to track the current state of that iterable, in particular when using it with infinite loops.
E.g. our use case is that we sample from multiple datasets that each loop indefinitely. Depending on their size, some datasets loop more often than others and it would be nice, e.g. at the end of a training, to see how many times each dataset was iterated over.

2023-08-21 12:40 UTC, AlirezaSohofi submitted a review, later dismissed
LG :+1: 
Could you please also update the version?

2023-08-28 13:50 UTC, MaxSchambach commented
@AlirezaSohofi I've bumped the version and added a test 👍

2023-08-28 15:29 UTC, AlirezaSohofi requested changes
Found a subtle bug

2023-08-28 15:37 UTC, AlirezaSohofi approved these changes
LG :+1:

2023-08-28 17:19 UTC, merged