CatalogKey can be used to index catalog
merantix-momentum/squirrel-core pull request #49
Opened 2022-06-03 09:59 UTC by AlpAribal

# Description

Makes it possible to get, set, and delete sources in a catalog using a `CatalogKey` or a `(id, version)` tuple.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All dependency changes have been reflected in the pip requirement files.

2022-06-03 16:35 UTC, AlirezaSohofi requested changes

2022-06-03 16:35 UTC, AlirezaSohofi commented on squirrel/catalog/catalog.py
> +                raise KeyError
please give an informative error message

2022-06-03 16:35 UTC, AlirezaSohofi commented on squirrel/catalog/catalog.py
> +                raise KeyError
would be cool to have the test case for this too

2022-06-03 16:35 UTC, AlirezaSohofi commented on squirrel/catalog/catalog.py
> +            if isinstance(identifier, str):
why do we need this additional check `if isinstance(identifier, str):` ?

2022-06-03 16:35 UTC, AlirezaSohofi commented on squirrel/catalog/catalog.py
> +    def __delitem__(self, identifier: Union[str, CatalogKey, Tuple[str, int]]) -> None:  # noqa D105
the behaviour might be unexpected, you can overwrite an existing version, or set and arbitrary version, etc, should we explain it some where?

2022-06-03 16:35 UTC, AlirezaSohofi commented on test/test_catalog/test_catalog.py
> +    """Test versioning a source in a Catalog using all allowed identifier types."""
please add test cases for `__delitem__`, `__contains__`, `__getitem__` for non-existing CatalogKey, and providing unsupported CatalogKey (e.g. non-string identifier?)

2022-06-07 08:15 UTC, AlpAribal commented on squirrel/catalog/catalog.py
> +            if isinstance(identifier, str):
We allow two types of identifiers:
1) `str`: Just the id of the catalog source, the user gets the version they want later on, e.g. `cat["my_id"][my_ver]`
2) `Tuple[str, int]`: This is the new format, basically either a `CatalogKey` or a tuple similar to it. This is what this PR introduces. The user can specify the version directly, e.g. `cat["my_id", my_ver]`.

To differentiate btw the two types, checking if identifier is a string is easier. If we check `isinstance(identifier, CatalogKey)`, then we do not cover the `Tuple[...]` case, and if we check `isinstance(identifier, Tuple)` then we do not cover the `CatalogKey` case. So, we check if identifier is string and if not we conclude that the identifier is tuple-like.

2022-06-07 08:17 UTC, AlpAribal commented on squirrel/catalog/catalog.py
> +    def __delitem__(self, identifier: Union[str, CatalogKey, Tuple[str, int]]) -> None:  # noqa D105
Which behavior exactly? The string identifier case is same as before. Do you mean we should remove all version also when a tuple identifier is provided?

2022-06-07 17:56 UTC, AlirezaSohofi submitted a review, later dismissed
LG :+1:

2022-06-08 09:56 UTC, merged