Create codeql-analysis.yml
merantix-momentum/squirrel-core pull request #52
Opened 2022-06-10 09:54 UTC by AlirezaSohofi

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-10 12:58 UTC, AlpAribal requested changes
Nice addition!

2022-06-10 12:58 UTC, AlpAribal commented on .github/workflows/codeql-analysis.yml
> +    #   ./location_of_script_within_repo/buildscript.sh
I don't think we need this part

2022-06-10 12:58 UTC, AlpAribal commented on .github/workflows/codeql-analysis.yml
> +    branches: [ "main" ]
We won't be checking PRs that merge into other PRs, right? Is that on purpose?

2022-06-10 13:53 UTC, AlirezaSohofi commented on .github/workflows/codeql-analysis.yml
> +    branches: [ "main" ]
No only on main

2022-06-10 15:36 UTC, AlpAribal commented
When I view the CodeQL check output, I see the following warning message:
```
An error occurred while trying to automatically install Python dependencies: Error: The process '/home/runner/work/_actions/github/codeql-action/v2/python-setup/auto_install_packages.py' failed with exit code 1
Please make sure any necessary dependencies are installed before calling the codeql-action/analyze step, and add a 'setup-python-dependencies: false' argument to this step to disable our automatic dependency installation and avoid this warning.
```
Could not find anything substantial about this warning though.

2022-06-21 12:45 UTC, AlpAribal reviewed
Now, codeql analysis succeeds without errors or warnings. If this is enough, then LGTM. A few points are not clear to me though:
1. How do I parse or see the analysis results? When I check the action output, I see neither any errors nor a "no errors found" text
2. Do we need to install the requirements before the analysis? If the analysis is done on the source code, then installing dependencies might not be necessary.

2022-06-21 15:23 UTC, AlpAribal commented on .github/workflows/codeql-analysis.yml
> +        python-version: '3.x'
We have `python_requires=">=3.8.0"`. Should we test with the smallest allowed version (3.8.x) or with the latest version (3.10.x)?

2022-06-21 16:53 UTC, AlirezaSohofi commented on .github/workflows/codeql-analysis.yml
> +    branches: [ "main" ]
updated the description :+1:

2022-06-21 16:55 UTC, AlirezaSohofi commented on .github/workflows/codeql-analysis.yml
> +        python-version: '3.x'
Let's leave it at `3.x`

2022-06-22 04:44 UTC, AlpAribal approved these changes
LGTM!

2022-06-22 08:04 UTC, merged