*add advanced store *reorganize sections *add icon,favicon
merantix-momentum/squirrel-core pull request #53
Opened 2022-06-10 15:31 UTC by pzdkn

# Description

*add advanced store 
*reorganize sections 
*add icon,favicon
* including alp's changes to the original store doc

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-13 08:21 UTC, AlpAribal reviewed
Sphinx gives a few warnings when building the docs, due to short underlines are broken ref links. You can check them out by running `sphinx-build ./docs ./docs/_build`. You can ignore the `WARNING: more than one target found for cross-reference ...` warnings, we are aware of these (they are coming from the use of the autoapi extension, do not have a solution for them now).

2022-06-13 08:21 UTC, AlpAribal commented on docs/advanced/store.rst
> +        IterableSource(range(N)).map(get_sample).batched(1000).async_map(store.set).join() # asynch writing to store
```suggestion
        IterableSource(range(N)).map(get_sample).batched(1000).async_map(store.set).join() # async writing to store
```

2022-06-13 08:21 UTC, AlpAribal commented on docs/advanced/store.rst
> +:py:class:`squirrel.store.SquirrelStore`  uses a concept called sharding (:ref:`usage/store:Sharding`) to efficiently store and load data.
```suggestion
:py:class:`squirrel.store.SquirrelStore` uses a concept called sharding (:ref:`usage/store:Sharding`) to efficiently store and load data.
```

2022-06-13 08:21 UTC, AlpAribal commented on docs/advanced/store.rst
> +    3. Randomizing during deep learning training: To shuffle the shards, one simply can shuffle the shard keys. That means, the more shards we have, the closer the shuffling process approaches a full
Could you have one sentence per line here and also in general? Shorter lines are more readable

2022-06-13 08:21 UTC, AlpAribal commented on docs/conf.py
> +html_logo = "_static/logo_xs.png"
Nice :+1:

2022-06-13 08:21 UTC, AlpAribal commented on docs/getting_started/installation.rst
> +=======
Sphinx likes underlines to be at least the same length as the title
```suggestion
============
```

2022-06-13 08:21 UTC, AlpAribal commented on docs/advanced/store.rst
> +The code snippet below implements a Store connecting a sqlite database. Here we can see that the concepts of sharding and serialization are not inherent to Store per se.
```suggestion
However, if you have different use-cases such as reading data via HTTP requests or retrieving from a database, you may need to implement your own Store.
The code snippet below implements a Store connecting to a SQLite database. Here we can see that the concepts of sharding and serialization are not inherent to Store per se.
```

2022-06-13 11:58 UTC, AlirezaSohofi commented on docs/usage/driver.rst
> +        my_driver = StoreDriver(store=SquirrelStore(url="path/to/data", serializer=MessagepackSerializer()))
the api of `StoreDriver` has changed to: `def __init__(self, url: str, serializer: SquirrelSerializer, **kwargs) -> None:`

2022-06-13 12:56 UTC, pzdkn commented
Hi, I have resolved the issues mentioned.

2022-06-13 15:08 UTC, AlpAribal requested changes
I like the explanations and examples, thank you! Left minor comments

2022-06-13 15:08 UTC, AlpAribal commented on docs/advanced/store.rst
> +:py:class:`squirrel.store.SquirrelStore` uses a concept called sharding (:ref:`usage/store:Sharding`) to efficiently store and load data.
`usage/store:Sharding` is not a valid reference now, maybe the label/title has changed?

2022-06-13 15:08 UTC, AlpAribal commented on docs/advanced/store.rst
> +    However, the main idea of increasing the “degree” of randomness, with increasing shard counts remains.
For numbered lists, I would just use `#.` notation so that we do not need to keep the count of bulletpoints ourselves. Also, there has to be an empty line before the bullet list. Then, for each bulletpoint, the texts should start at the same indentation level (e.g. for the first bulletpoint, "read and write operations ..." has to be aligned with "Parallelizing ...", not with "1.")

2022-06-13 20:40 UTC, AlirezaSohofi requested changes
Thanks looks very good, left some minor comments :+1:

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/advanced/store.rst
> +       Internally there is another mechanism to shuffle samples within the shards (reference).
If this refer to the `.shuffle()` method of `Composable`, it actually shuffles samples on the stream.

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/advanced/store.rst
> +.. code-block:: python
no strong opinion, but seems to me that this fits better as a notebook tutorial which is then linked here.

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/getting_started/installation.rst
> +The supported packages are: `gcp`, `s3`, `parquet`, `zarr`, `dask`, `torch`
`dev` and `doc`

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/getting_started/introduction.rst
> +    Update merantix/squirrel-datasets to merantix-momentum/squirrel-datasets-core
please remove this line

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/usage/driver.rst
> +    If you have a dataset in MessagePack or jsonl format, you can load your data directly by using a StoreDriver and
Please remove this note as it's not relevant anymore because of the recent changes on the main, sorry for the confusion

2022-06-13 20:40 UTC, AlirezaSohofi commented on docs/advanced/store.rst
> +Sharding
describing what shards and samples are should be in the basic usage as it concerns all users. The considerations may live here. 

I would suggest to provide a simple code snippets to illustrate a sample and a shard, and also pointing out to `squirrel.constants.SampleType` and `squirrel.constants.ShardType`

2022-06-14 08:11 UTC, pzdkn commented on docs/advanced/store.rst
> +       Internally there is another mechanism to shuffle samples within the shards (reference).
Then I'll reference to .shuffle(), if that's fine for you

2022-06-14 08:12 UTC, pzdkn commented on docs/advanced/store.rst
> +.. code-block:: python
True, but the integration of notebooks is an open discussion, right?

2022-06-14 09:58 UTC, AlirezaSohofi commented on docs/advanced/store.rst
> +However, if you have different use-cases such as reading data via HTTP requests or retrieving from a database, you may need to implement your own Store.
```suggestion
:py:class:`AbstractStore` defines an abstraction to provide a key/value api on top of any storage. It may optionally use :py:class:`SquirrelSerializer`. If you have a specific use-case which is not natively provided such as reading data via HTTP requests or retrieving from a database, you may need to implement your own Store.
```

2022-06-14 14:11 UTC, AlpAribal requested changes

2022-06-14 14:11 UTC, AlpAribal commented on docs/advanced/store.rst
> +:py:class:`AbstractStore` defines an abstraction to provide a key/value api on top of any storage.
```suggestion
:py:class:`AbstractStore` defines an abstraction to provide a key/value API on top of any storage.
All stores are expected to obey this API.
```

2022-06-14 14:11 UTC, AlpAribal commented on docs/advanced/store.rst
> +Squirrel provides two serializers formats: :py:class:`MessagepackSerializer` and :py:class:`JsonSerializer`.
```suggestion
Squirrel provides two serializers: :py:class:`MessagepackSerializer` and :py:class:`JsonSerializer`.
```

2022-06-14 14:11 UTC, AlpAribal commented on docs/advanced/store.rst
> +faster to encode and decode and produces smaller files. Messegepack is the recommended format,
```suggestion
faster to encode and decode and produces smaller files. Messagepack is the recommended format,
```

2022-06-14 14:11 UTC, AlpAribal commented on docs/advanced/store.rst
> +unless you have specific constraints or requirements. To demonstrate that Messagepack produces smaller files, we included the code
```suggestion
unless you have specific constraints or requirements. To demonstrate that Messagepack produces smaller files, we include the code
```

2022-06-14 14:11 UTC, AlpAribal commented on docs/advanced/store.rst
> +:py:class:`squirrel.store.SquirrelStore` uses a Serializer to store shards of samples as singular files onto the storage backend (e.g. filesytem, object store, etc.).
```suggestion
:py:class:`squirrel.store.SquirrelStore` uses a Serializer to store shards of samples as singular files onto the storage backend (e.g. filesystem, object store, etc.).
```

2022-06-14 14:24 UTC, pzdkn commented on docs/advanced/store.rst
> +      store = SQLiteStore('temp.db')
works!

2022-06-14 14:26 UTC, pzdkn commented on docs/getting_started/introduction.rst
> +#. Check out what is possible by looking at some `examples <https://github.com/merantix-momentum/squirrel-datasets-core/tree/main/examples>`_
The 'Chek out' at the start of the sentence should remain, right ?

2022-06-14 14:43 UTC, AlpAribal commented on docs/getting_started/introduction.rst
> +#. Check out what is possible by looking at some `examples <https://github.com/merantix-momentum/squirrel-datasets-core/tree/main/examples>`_
Above the bullet point list, we say "See" and all bullet points continue as if there is a "see" before them. Hence, I think the check out is not necessary

2022-06-14 14:44 UTC, AlpAribal submitted a review, later dismissed
LGTM :+1:

2022-06-15 11:00 UTC, AlirezaSohofi commented on docs/advanced/store.rst
> +All stores are expected to obey this API.
```suggestion
All stores should conform to this abstraction.
```

2022-06-15 11:04 UTC, AlirezaSohofi commented on docs/getting_started/installation.rst
> +The supported packages are: `gcp`, `s3`, `parquet`, `zarr`, `dask`, `torch`, `dev`, `doc`
missing dependencies: `azure`
`parquet` is not a valid dependency.

2022-06-15 11:07 UTC, AlirezaSohofi commented on docs/usage/store.rst
> +Sharding
```suggestion
Sample and Shard
```

2022-06-15 11:09 UTC, AlirezaSohofi commented on docs/usage/store.rst
> +
I suggest to move this up to line 39, sample and shard is mentioned there.

2022-06-15 11:11 UTC, AlirezaSohofi commented on docs/usage/store.rst
> +Shards stores a predetermined amount of samples given through the shard size in a fixed order.
```suggestion
Shard is a collection of samples, it stores a predetermined number of samples in a fixed order.
```

2022-06-15 11:16 UTC, AlirezaSohofi commented on docs/usage/store.rst
> +:py:class:`squirrel.store.SquirrelStore` uses a concept called sharding to efficiently store and load data.
here please say a sentence about what a sample is. something like this: Sample is any python object, usually a dictionary, representing a single training sample for model training. It may include a numpy array and basic data types.

2022-06-15 15:50 UTC, pzdkn commented on docs/usage/store.rst
> +
I don't see any mentions of samples and shards at line.39? Is is where SquirrelStore is introduced?

2022-06-15 16:34 UTC, AlirezaSohofi approved these changes
LG, thanks a lot for the effort :+1:

2022-06-15 16:59 UTC, merged