minimal code example plus a diagram illustrating user-facing classes
merantix-momentum/squirrel-core pull request #54
Opened 2022-06-13 19:09 UTC by AlirezaSohofi

# Description

Add a `Architecture overview` page to the doc with a complete data loading pipeline and it's equivalent UML diagram. 

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-14 07:49 UTC, pzdkn commented on docs/usage/architecture_overview.rst
> +For instance, an implementation of the :py:class:`Drive` may not need or choose to not use :py:class:`SquirrelStore`
Spelling error in Driver: `the abstract classes (i.e. :py:class:`Driver`, :py:class:`AbstractStore`, :py:class:`SquirrelSerializer`).`

2022-06-14 07:52 UTC, pzdkn commented on docs/usage/architecture_overview.rst
> +here is a complete data loading pipeline:
-> Here is a complete data loading pipeline:

2022-06-14 08:02 UTC, pzdkn commented on docs/usage/architecture_overview.rst
> +contains all necessary information to instantiate an abject of type :py:class:`Driver`. :py:class:`Driver` may have
abject -> object

2022-06-14 08:02 UTC, pzdkn commented on docs/usage/architecture_overview.rst
> +The following diagram illustrating (a simplified and slightly idealized) view on the relationships between these
illustrating -> illustrates

2022-06-14 08:24 UTC, pzdkn commented
Thanks Ali, it would looks quite nice and can maybe even act as an introduction?

2022-06-15 07:37 UTC, AlpAribal requested changes
Much needed summary, thank you, added few comments

2022-06-15 07:37 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +    train_loader = DataLoader(train_data, batch_size=None)
Additional explanation and/or pointers for some lines here would be useful (some points I can think of are: what does from_plugins do, what is a plugin, where is "imagenet" coming from, what kind of funcs are `transform` and `filter_func`). Maybe converting the following paragraph to a step-by-step explanation format would be better?

2022-06-15 07:37 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +The following diagram illustrating (a simplified and slightly idealized) view on the relationships between these
```suggestion
The following diagram illustrates a (simplified and slightly idealized) view of the relationships between these
```

2022-06-15 07:37 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +For instance, an implementation of the :py:class:`Drive` may not need or choose to not use :py:class:`SquirrelStore`
```suggestion
For instance, an implementation of the :py:class:`Drive` may not need to or may choose not to use :py:class:`SquirrelStore`
```

2022-06-15 07:38 UTC, AlpAribal commented
If you are using VSCode, I found the Esbonio (id: swyddfa.esbonio) extension quite useful for previewing sphinx docs.

2022-06-15 10:07 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +    train_loader = DataLoader(train_data, batch_size=None)
I see, yes it is clear :+1:

2022-06-15 10:08 UTC, AlpAribal approved these changes
LGTM

2022-06-15 10:08 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +    )
```suggestion
    train_data = (
        catalog["imagenet"]  # CatalogSource
        .get_driver()  # Driver
        .get_iter()  # Composable
        .map(lambda x: transform(x))  # Composable
        .filter(lambda x: filter_func(x))  # Composable
    )  # Composable
```

2022-06-15 11:34 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +        catalog["imagenet"] # CatalogSource
```suggestion
    catalog = Catalog.from_plugins()  # Catalog
    train_data = (
        catalog["imagenet"]  # CatalogSource
```

2022-06-15 11:44 UTC, AlpAribal commented on docs/usage/architecture_overview.rst
> +        %% realiazation
```suggestion
        %% realization
```

2022-06-15 12:54 UTC, AlpAribal approved these changes

2022-06-15 12:59 UTC, merged