First draft of advanced section for iterstreams
merantix-momentum/squirrel-core pull request #55
Opened 2022-06-21 09:43 UTC by pzdkn

* architecture overview
* composbale class
* chaining iterables
* special composables

# Description

First draft on advanced section of iterstream 

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-21 09:47 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +A very similar class is the :py:class:`__AsyncMap` class ...
So ` _AsyncMap` is mostly used with `async_map ` method, but ` _Iterable` is also used with `map` (but other methods also return ` _Iterable`).  Is this a distinction we want to mention here?

2022-06-21 09:47 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +* :py:meth:`squirrel.iterstream.base.Composable.batched`: explaination
Listing all functions is maybe a bit too verbose ?

2022-06-21 09:48 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +.. mermaid::
Not sure if this diagram in itself is so telling

2022-06-21 11:30 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +            callback: Callable
```suggestion
            callback: Callable
            int buffer
            int max_workers
            Executor executor
```

2022-06-21 11:30 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +.. mermaid::
Please include `AsyncContent` and its relationship with `_AsyncMap`

2022-06-21 11:30 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +* :py:meth:`squirrel.iterstream.base.Composable.batched`: explaination
agree

2022-06-21 11:30 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +.. admonition:: to vs compose
I suggest to make this a dedicated section about extending iterStream with user defined iterables.

2022-06-21 11:30 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +
Open the section with a sentence about what iterstream api aims to do: chaining iterators. The the example of chaining generators, then provide the equivalent implementation with `.compose(MyIterable)`, then explain the control flow (maybe with some print statements in the init and iter methods). Then explain that public methods on Composable such as map and filter are using internal classes for wrapping user defined function. After this the UML diagram will make more sense.

2022-06-21 11:54 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +
- It seems like we are making a difference beween chaining iterators and chaining generators. Is there a difference?
- What is `.compose(MyIterable)` equivalent to ? My understanding is that it constructs a new Composable with MyIterable. 
- What should the code examples show here ? That we can chain operations ? That the order is reversed ?

2022-06-23 10:42 UTC, AlirezaSohofi requested changes

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +The IterStream module provides functionalities to chain operations on iterables. This functionality
```suggestion
The IterStream module provides functionalities to chain iterables. This functionality
```

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +is provided through the mix-in class :py:class:`Composable`, which implements methods such as map or filter.
Composable is not mix-in

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +The nice thing about it is that all operations are done lazily, that is no computation is executed until we ask for it.
more clear wording here, maybe say squirrel pipeline is lazy. Then before hand, the term `pipeline` should be defined, probably best explained by an example

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +for the transformations such as a large network for preprocessing or a database connection.
what does `large network for preprocessing` mean?

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    Create Add_1
the print statement for this is missing in the code?

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +Most classes inherit from `Composable` to implement methods for stream manipulation.
mention that these are internal classes not meant to be used by users

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +provides a good example usage. Other special `Composable` classes such as :py:class:`squirrel.iterstream.torch_composables.SplitByWorker`
```suggection
provides an example. Other special `Composable` classes such as :py:class:`squirrel.iterstream.torch_composables.SplitByWorker`
```

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +An alternative way of chaining operations is via :py:meth:`squirrel.iterstream.base.Composable.compose`.
please highlight this, maybe by adding a dedicated sub-section, that this is the way to customize and extend iterstream api, and that it is meant to be used when the standard Composable methods are insufficient to express the logic. 

please also mention that if pipeline should be passed to tut.DataLoader, is must be picklable, and if the pipeline contains a non-picklable object such as an instance of a fsspec filesyste, the instantiation should happen in the iter method.

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +chaining stream manipulations. The difference is that `_AyncMap` deals with asynchronous execution. We show a non-exhaustive UML
a bit more on what `_AsyncMap` does is helpful. 

Please mention that the order is preserved with `_AsyncMap`, maybe worth mentioning in the basic usage. Here we can explain the internal queue of size `buffer` that contains `AsyncContent` objects

2022-06-23 10:42 UTC, AlirezaSohofi commented on docs/index.rst
please add integration section

2022-06-23 11:39 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +for the transformations such as a large network for preprocessing or a database connection.
extract word embeddings or image features from a large model like bert

2022-06-23 11:44 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +The nice thing about it is that all operations are done lazily, that is no computation is executed until we ask for it.
speaking of which, what is a `pipeline` ? Is it simply a chain of Composables ?

2022-06-24 09:35 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +* *Organization*: :py:meth:`shuffle`, py:meth:`batch`, py:meth:`take`. THe methods are used to order and organize the stream.
shuffle and batch are part of transformation.
take is a terminal operation
Instead of `Organization`, there should be another kind `Source`, should be mentioned as the first class I guess, and includes e.g. `IterableSource`.

2022-06-24 09:35 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +* *Terminal* : :py:meth:`join`, py:meth:`collect`. These methods are used to materialize the stream.
Materialize it not technically correct, as items in the stream are already in memory and materialized. Terminal operations in fact consume the stream and turn in into a non-composable object, e.g. None and List.

2022-06-24 09:35 UTC, AlirezaSohofi commented on docs/index.rst
> +   integration/integration.rst
```suggestion
   integration/PyTorch.rst
   integration/Monitoring_MLFlow_wandb.rst
   integration/spark.rst
   integration/dask.rst
```

2022-06-24 11:43 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +* *Organization*: :py:meth:`shuffle`, py:meth:`batch`, py:meth:`take`. THe methods are used to order and organize the stream.
what's the function of source ?

2022-06-24 11:44 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +
hmm what do we want to show here ? This chain of generators has the same lazy execution property as composables, right?

2022-06-24 11:46 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +* *Terminal* : :py:meth:`join`, py:meth:`collect`. These methods are used to materialize the stream.
so the whole iterator is loaded in memory ? what is the benefit of lazy execution then ?

2022-06-24 15:22 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +* *Source*: :py:meth:`source_``. Source defines the source iterable on which transformations are applied.
```suggestion
* *Source*: The first node in the stream that generates items or wraps an iterable, for instance :py:class:`IterableSource`.

```

2022-06-24 15:22 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +* *Transformations* : :py:meth:`map`, :py:meth:`filter`, :py:meth:`shuffle`, :py:meth:`batch`. These methods can be used to apply a transformation over the stream.
```suggestion
* *Transformations* : Provide a way to apply transformations on items in the stream, such as :py:meth:`map` and :py:meth:`filter`, or manipulate the stream itself, such as :py:meth:`shuffle`, :py:meth:`batched`. 
```

2022-06-24 15:22 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    (x + 1) * 10: [10, 20, 30]
:+1:

2022-06-24 15:22 UTC, AlirezaSohofi commented on docs/usage/iterstream.rst
> +from the queue by iterating over the :py:class:`_AsyncMap` object.
I'd suggest to move this to the advanced doc

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    from squirrel.iterstream import IterableSource
this import statement is not used here, please move to the next code block where it's used

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +In the example above we see how Composables are chained. We also call this chain of Composables **stream**. The executions are
at this point it's still not shown that `it` is composable. I suggest the following:

```
assert isinstance(IterableSource(range(3)), Composable)
assert isinstance(IterableSource(range(3).map(add_1)), Composable)
assert isinstance(IterableSource(range(3).map(add_1).map(mult_10)), Composable)
```

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +            yield x + 1
wrong indentation

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    #. We need to instantiate a expensive resource only once in the constructor e.g. a database connection or a R-CNN feature extractor.
```suggestion
    #. We need to instantiate an expensive resource such as a database connection or a R-CNN feature extractor only once for the entire stream instead of once per item. In this case it is advisable to instantiate this resource in the `__iter__` method of your custom class. One advantage is that the object is only instantiated once iterating over the stream starts. Additionally, if this resource is a non-picklable object, the stream can still be pickled before the iteration starts (e.g. in the multiprocessing context). 

```

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +When using `compose()` note that the order of calling the `__iter__` method is from right ot left.
Not only the case for `compose()`, but for all other methods too, e.g. the same is the case when you have `map()`, but it's just easier to illustrate the concept with print statements with `compose`

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +When using `compose()` note that the order of calling the `__iter__` method is from right ot left.
maybe a more general statement, that the following example illustrates the control flow and order of instantiation and iterations of a composable object that comprises several transformations.

2022-06-27 13:29 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    Note that PyTorch Dataloader requires the iterable passed to be pickable when using multi-processing. That is, our custom Composable
probably better to mention this in the PyTorch integration section

2022-06-27 15:33 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +    Note that PyTorch Dataloader requires the iterable passed to be pickable when using multi-processing. That is, our custom Composable
This is already explained in the PyTorch integration section, I thought of it more like a link/hint. Maybe it's redundant though, we can just remove it.

2022-06-27 15:34 UTC, pzdkn commented on docs/advanced/iterstream.rst
> +In the example above we see how Composables are chained. We also call this chain of Composables **stream**. The executions are
It is a bit verbose though. Is it maybe enough to describe that IterableSource inherits from Composable ?

2022-06-27 15:51 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +            async_map(callback, buffer, max_workers, executor) _Iterable
```suggestion
            async_map(callback, buffer, max_workers, executor) _AsyncMap
```

2022-06-27 15:51 UTC, AlirezaSohofi commented on docs/integration/dask.rst
> +    it = IterableSource([1, 2, 3]).async_map(io_bound, executor=client)
`io_bound` not defined

2022-06-27 16:01 UTC, AlirezaSohofi commented on docs/integration/spark.rst
> +Squirrel offers functionalities to read and write to the store using Spark. We provide tutorials for
```suggestion
:py:class:`SquirrelStore` is designed to provide easy read parallelization, and also write parallelization. To learn about how it can be used along e.g. Spark, refer to the following tutorials:
```

2022-06-27 16:13 UTC, AlirezaSohofi commented on docs/advanced/iterstream.rst
> +    classDiagram
please signal that Composable is abstract

2022-06-27 16:16 UTC, AlirezaSohofi commented on docs/integration/monitoring.rst
> +Monitoring
Monitoring with mlflow and wandb

the name on the file should be also updated I guess

2022-06-28 09:20 UTC, pzdkn commented
I have read the CLA Document and I hereby sign the CLA

2022-06-29 12:48 UTC, AlirezaSohofi approved these changes
LG, thanks for the great work :+1:

2022-06-29 16:48 UTC, AlirezaSohofi approved these changes

2022-06-29 17:42 UTC, merged