Update Doc-String of MapDriver.get_iter
merantix-momentum/squirrel-core pull request #61
Opened 2022-06-27 18:26 UTC by kai-tub

- Better document the behavior of `max_workers` and link to official `ThreadPoolExecutor` documentation.
- Update `*_map` doc-strings that use `ThreadPoolExecutor` and link to official `ThreadPoolExecutor` documentation.

Fixes #60  issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [X] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [X] I have kept the PR small so that it can be easily reviewed  
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-28 07:45 UTC, winfried-loetzsch commented
Hi @kai-tub thanks for your contribution! This looks good already

2022-06-28 07:54 UTC, winfried-loetzsch requested changes
Just a few typos, otherwise looks good!

2022-06-28 07:54 UTC, winfried-loetzsch commented on squirrel/driver/driver.py
> +                Defaults to None.rea
```suggestion
                Defaults to None.
```

2022-06-28 07:54 UTC, winfried-loetzsch commented on squirrel/driver/driver.py
> +                `None` has a special meaning in this context and uses an internal heuristicZ for the number of workers.
```suggestion
                `None` has a special meaning in this context and uses an internal heuristic for the number of workers.
```

2022-06-28 08:13 UTC, AlirezaSohofi requested changes
Thanks looks very good, left some minor comments :+1:

2022-06-28 08:13 UTC, AlirezaSohofi commented on squirrel/driver/driver.py
> +                Defaults to None.rea
```suggestion
                Defaults to None.
```

2022-06-28 08:13 UTC, AlirezaSohofi commented on squirrel/driver/driver.py
> +                `None` has a special meaning in this context and uses an internal heuristicZ for the number of workers.
```suggestion
                `None` has a special meaning in this context and uses an internal heuristic of :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>` for the number of workers.
```

2022-06-28 08:22 UTC, AlpAribal requested changes
Thank you for the PR and also for the smaller improvements here and there!

Actually, if an executor is provided, `max_workers` is not used (since the number of workers was already set when instantiating the executor). This is currently not mentioned in the docs and it would be nice to add this information as well.

I have made a few suggestions on how/where to include this info. These are only suggestions though, feel free to use your own words/structure.

2022-06-28 08:22 UTC, AlpAribal commented on docs/usage/Iterstream.rst
> +    it = IterableSource([1, 2, 3]).async_map(io_bound, executor=tpool, max_workers=4).async_map(io_bound)
I suggest keeping `max_workers` here, removing `tpool` and explaining how to specify an `executor` below the code block (which you have already done)
```suggestion
    it = IterableSource([1, 2, 3]).async_map(io_bound, max_workers=4).async_map(io_bound)
```

2022-06-28 08:22 UTC, AlpAribal commented on docs/usage/Iterstream.rst
> +the `executor` to select a reasonable upper bound.
We should make explicit when exactly `max_workers` is being used.
```suggestion
If an executor is not provided, the argument `max_workers` can be used to control the level of parallelism.
This argument defines the maximum number of workers used by the ThreadPoolExecutor
that will be instantiated by squirrel.
By default, `max_workers=None` relies on an internal heuristic of
ThreadPoolExecutor to select a reasonable upper bound.
```

2022-06-28 08:22 UTC, AlpAribal commented on docs/usage/Iterstream.rst
> +See the documentation of the `executor` for more details.
```suggestion
See the documentation of the `executor` for more details.
If an `executor` is specified, then `max_workers` is ignored.
```

2022-06-28 08:22 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +            max_workers (int): number of workers in the :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`
```suggestion
            max_workers (int): number of workers in the :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`
                `max_workers` is only used when `executor` is not provided.
```

2022-06-28 09:11 UTC, kai-tub commented
Ah, I completely missed that max_workers is only applied if `executor` is not changed.
I will need some time to update the documentation in various places then.
Once I am done, I will remove `[WIP]` from the title again.

2022-06-28 09:12 UTC, kai-tub commented on docs/usage/Iterstream.rst
> +    it = IterableSource([1, 2, 3]).async_map(io_bound, executor=tpool, max_workers=4).async_map(io_bound)
:+1: I will add this to the documentation

2022-06-28 09:34 UTC, AlpAribal commented
> Wouldn't it be "more obvious" to call `max_workers` `max_threads` instead?

In hindsight, yes, it sounds more intuitive to me. On the other hand, `ThreadPoolExecutor` also calls its "n_threads" argument `max_workers`, so maybe using the same convention is better. I do not have a strong feeling regarding this. I would wait a while before changing the name, and try to validate if the naming does create more and more confusion among users.

2022-06-29 06:27 UTC, kai-tub commented
A third option would be to add a simple check if `max_workers is not None and executor is not None` and raise a UserWarning that the `max_workers` argument will be ignored.

2022-06-29 16:48 UTC, kai-tub commented
I have read the CLA Document and I hereby sign the CLA

2022-07-01 06:47 UTC, AlpAribal requested changes
Very nice examples and explanations, thank you! I only left a few minor comments.

2022-07-01 06:47 UTC, AlpAribal commented on squirrel/driver/driver.py
> +            max_workers (int, optional): If `max_workers`  is equal to 0 or 1, :py:meth:`~squirrel.iterstream.Composable.map`
```suggestion
            max_workers (int, optional): If `max_workers` is equal to 0 or 1, :py:meth:`~squirrel.iterstream.Composable.map`
```

2022-07-01 06:47 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +            max_workers (int): number of workers in the :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`
```suggestion
            max_workers (int): number of workers in the :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`.
```

2022-07-01 06:47 UTC, AlpAribal commented on docs/usage/Iterstream.rst
> +In the above example, two :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`'s
```suggestion
In the above example, two :py:class:`ThreadPoolExecutor <concurrent.futures.ThreadPoolExecutor>`\s
```

2022-07-01 08:10 UTC, kai-tub commented
Sorry for those typos...
Do you have any recommendations on how one could catch them automatically?
Can you somehow export the document as a plain text file and run a grammar-checker on it?
I am using VScode if you happen to know a good extension.
Thanks :)

2022-07-01 08:14 UTC, AlpAribal commented
> Sorry for those typos... Do you have any recommendations on how one could catch them automatically? Can you somehow export the document as a plain text file and run a grammar-checker on it? I am using VScode if you happen to know a good extension. Thanks :)

I am using Code Spell Checker (extension id: streetsidesoftware.code-spell-checker). Just personal preference though, there are probably a bunch of other options as well.

2022-07-01 08:37 UTC, kai-tub commented
Ah yes.
Merge conflicts... The arch-nemesis of junior developers...

2022-07-01 09:25 UTC, kai-tub commented
I think I might have overwritten the previous changes in iterstream.
I will have a look at it again once I have some left-over time.
The changed name made it kinda hard to follow what changed between commits.
Please do not merge without reviewing it.

2022-07-01 14:53 UTC, pzdkn requested changes
Thanks @kai-tub for your contribution :) It seems you some merge-conflict, I left some comment on what was overwritten and what was unintentionally moved.

2022-07-01 14:53 UTC, pzdkn commented on docs/usage/iterstream.rst
> -Stream Processing Methods
@kai-tub , I think this shouldn't be overwritten

2022-07-01 14:53 UTC, pzdkn commented on docs/usage/iterstream.rst
> -To see how you can chain custom Composables with `compose()`, see the advanced section for :ref:`IterStream <advanced/iterstream:IterStream>`.
This should also remain

2022-07-01 14:53 UTC, pzdkn commented on docs/usage/iterstream.rst
> +Cluster-mode
This has been moved to the integration section

2022-07-01 14:53 UTC, pzdkn commented on docs/usage/iterstream.rst
> +Just-in-time compilation with numba
This has been also moved

2022-07-01 14:53 UTC, pzdkn commented on docs/usage/iterstream.rst
> +Performance Monitoring
Also moved

2022-07-04 06:42 UTC, kai-tub commented on docs/usage/iterstream.rst
> +Just-in-time compilation with numba
I cannot find the section where this has been moved.
It seem like the jit numba discussion has been removed altogether?

2022-07-04 06:49 UTC, kai-tub commented
I hope that the PR is now finally ready to be merged. :)
I would like to thank everyone who was involved in the process for the patience to resolve the merge conflict and for fixing quite a few typos in my commits.
Please feel free to squash the commits and re-write the commit message however you like.
I feel like the number of commits from this PR would pollute the commit history of other files without having any clear benefit.

Thank you all again for your help!

2022-07-04 14:49 UTC, AlpAribal commented
/gcbrun

2022-07-04 15:15 UTC, pzdkn approved these changes
LGTM

2022-07-05 13:06 UTC, merged