[WIP] Store the processing steps in a stream
merantix-momentum/squirrel-core pull request #64
Opened 2022-06-28 14:05 UTC by pzdkn

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ x] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-06-29 08:36 UTC, AlirezaSohofi reviewed
Looks very good :1st_place_medal:

2022-06-29 08:36 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    assert len(it.history) == 2
why not 3?

2022-06-29 08:36 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    assert it.history[0]['args'][0] == 'add_1' and it.history[1]['args'][0] == 'mult_10'
suggestion: `add_1` --> `my_project.my_module.my_func`

2022-06-29 08:36 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        self.history = []
history should be private

2022-06-29 08:36 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +                'kwargs': kwargs}
would be cool if we can include some information about the git hash

2022-07-04 12:53 UTC, AlpAribal commented
> The alternative approach is to loop until no `source` attribute exists anymore and log the processing steps in the loop. What do you prefer?

I would tend towards this lazy approach but do not feel strong enough to reject the current solution.

2022-07-04 15:55 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        self._history = []
please also add a getter property to retrieve the history.

2022-07-04 15:56 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        self._history = []
Maybe `steps` is a more descriptive name than `history`.

2022-07-04 16:02 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
Source can be something other than `Composable`, e.g. the `IterableSource` wraps an iterable or a callable.

2022-07-04 16:03 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
Note that an `IterableSource` is also a `Composable`

2022-07-04 16:13 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
Then I probably did not understood your point correctly, I thought you mean checking the `source` attribute of the `Composable` object is `Composable`, which is the case for intermediate steps of the pipeline but not necessarily for the first step (e.g. `IterableSource`).

2022-07-04 16:19 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        self._history = []
steps is more fitting, true!

2022-07-04 16:26 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
I think we still don't get around to call `add_to_hist()` in `.to()` and. `.compose()` as we also want to log the function and function parameters, right?

2022-07-04 16:27 UTC, pzdkn commented on test/test_iterstream/test_stream.py
> +                    .collect()
thanks for the hint 😄

2022-07-04 16:41 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
With the current solution, in `Composable.to()`, we have:
```python
it = _Iterable(self, f, *args, **kw)
it.add_to_history(self, f, *args, **kw)
```
So, we first create a new Composable and then add the previous Composable to its history. To me, having a design where the addition to history is separated from the instantiation of the Composable is unwanted since
1. I can forget to add the parent to history when I create a new method, say `Composable.my_new_method()`, in which I create a new Composable and return this newly created object (similar to `.to()`)
2. We kind of signal that it is ok/expected to manage the history from the outside, i.e. the Composable itself does not know how the history is managed, we have to manage it for it when we are creating it

Having the separation can lead to unexpected results. Consider the following case:
```python
def add_1(x):
    return x + 1

def mult_10(x):
    return x * 10

it = IterableSource([1, 2, 3]).map(add_1).map(mult_10)
it2 = IterableSource(it)

len(it._history)  # 3
len(it2._history)  # 1
```
Here, for `it2`, I would expect a history of length 4, now we get 1 since `it2` is not aware that there actually is some history before itself and no one is managing the history for it.

What I suggest is that Composable checks whether its source is another Composable (the parent). If this is the case, it sets its own history as the history of the parent + one more step.

2022-07-05 07:45 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
What I don't quite understand is how you can retrieve the function and functional arguments from the constructor of `Composable` as it only receives `source`.

2022-07-05 12:10 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +        self.add_to_history(self, self.__class__)
We can define a `Compoasble._add_self_to_history()` method, which is called in `Composable.init()` to, ehm, add self to history. Then, the subclasses (`_Iterable`, `_AsyncMap`, `_LoopIterable`, ...) can override this method, if necessary, such as the case you point out with `_Iterable`.

2022-07-06 13:07 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +        self._add_to_steps()
How about calling this method in `steps` property? We can set `self._step = None` here and then
```python
    @property
    def steps(self) -> t.List[t.Dict[str, t.Union[str, t.Dict]]]:
        """Getter for steps"""
        if self._steps is None:
            self._add_to_steps()
        return self._steps
```
The reason I am suggesting this is that now the subclasses of `Composable` need to know that they should set their variables before calling `super().__init__()` in order for their variables to be shown in `steps`. I see that we have considered this in `_Iterable` but there are other subclasses as well: `_LoopIterable`, `_AsyncMap`, `_NumbaMap`.

Another plus is  that we won't be keeping unnecessary memory if the user does not care about the steps.

It would also be nice to have tests for checking the steps args for each Composable subclass.

2022-07-06 13:07 UTC, AlpAribal commented on pyproject.toml
> +include = '\.pyi?$'
Is this change on purpose?

2022-07-06 13:07 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +            "git_version": subprocess.check_output(["git", "describe"]).strip().decode(),
This fails if we are running squirrel outside a git repo. If we are to keep this, we should wrap this with a try/except.

2022-07-06 13:24 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        self._add_to_steps()
yeah, quite a nice idea. Thanks :)

2022-07-06 13:27 UTC, pzdkn commented on pyproject.toml
> +include = '\.pyi?$'
Semi, I tried to change my black config back to default. I will revert it back.

2022-07-07 08:12 UTC, AlpAribal commented on squirrel/iterstream/base.py
> +                class_args[k] = [get_callable_name(obj) for obj in v]
I am asking this to better understand the use case.
- If we want steps to have a neat string form / representation, then we can make `get_callable_name` recursive so that all iterables are further prettified
- If we want steps (and all args of the steps) to be programmatically accessible (so that I can maybe test a function arg in the pipeline when debugging, e.g. `it.steps[-1]["class_args"]["args"][0](my_test_input)`, then leaving functions as they are might be better
@pzdkn @AlirezaSohofi wdyt?

2022-07-07 08:12 UTC, AlpAribal commented on test/test_iterstream/test_stream.py
> +        """Mult 10 to x"""
```suggestion
        """Mult x with 10"""
```

2022-07-08 14:40 UTC, pzdkn commented on squirrel/iterstream/base.py
> +                class_args[k] = [get_callable_name(obj) for obj in v]
- It's true, it's targeting the `_Iterable` class.
- Not really sure what the recursive solution should look like. Do you mind elaborating @AlpAribal ?

2022-07-08 16:07 UTC, AlirezaSohofi requested changes
There are some remaining issues:
1. `len(IterableSource([1,2,3]).compose(MyIter).steps) == 2` --> False. Please investigate why and add test for it
2. if there is a big object, say a list, in the arguments, it must be excluded. We can try to provide some information like length. `steps` should only contain small objects so that we can log it easily. An example: `IterableSamplerSource([[1,2,3], [11,22,33]]).steps`
3. `steps` should only contains basic data types, otherwise it might not be possible to log it. This must be checked for user provided arguments (similar to `2`). Example in `2` contains a `rng` object.
4.  `FilePathGenerator("/home/user/data").steps` gives you the url in clear text which could be a security issue. This should be somehow masked.

2022-07-08 16:11 UTC, AlirezaSohofi commented
> 4\. `FilePathGenerator("/home/user/data").steps` gives you the url in clear text which could be a security issue. This should be somehow masked.

It would be useful to let the user decide on this. For that, `steps` should be changed to `steps(secure=False)`

2022-07-08 16:33 UTC, pzdkn commented
> 3\. `steps` should only contains basic data types, otherwise it might not be possible to log it. This must be checked for user provided arguments (similar to `2`). Example in `2` contains a `rng` object.

So we would only store primitive data-types? For Iterables, we store the length?

2022-07-19 14:38 UTC, closed without merging