Include source behaviour from polls
merantix-momentum/squirrel-core pull request #67
Opened 2022-07-12 09:21 UTC by pzdkn

# Description

Include the desired behaviour for passing a source argument when using `compose()`:

- We can define constructor for custom Composable, but must leave out source argument
- We can leave out constructor, and use the base one. 

Fixes # issue

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-07-12 10:18 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +            assert inspect.signature(constructor).parameters["source"].default is None
we should disallow having `source` in the parameters, so raise at `45`.

2022-07-12 10:39 UTC, AlirezaSohofi requested changes

2022-07-12 10:39 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +        def __init__(self):
please add a case that has arguments in the init

2022-07-12 10:39 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +        def __init__(self, source: t.Union[t.Iterable, t.Callable]):
please add a case `source=None` in the init. It should fail.

2022-07-12 10:39 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +            assert inspect.signature(constructor).parameters["source"].default is None
Please raise an informative exception

2022-07-12 11:09 UTC, pzdkn commented on squirrel/iterstream/base.py
> +            assert inspect.signature(constructor).parameters["source"].default is None
If we don't implement a constructor, then the base constructor is used and this one will have a default source set to None. 

As far as I understand we wanted to still support the case of omitting the constructor, wdyt @AlirezaSohofi ?

2022-07-12 11:42 UTC, pzdkn commented on test/test_iterstream/test_stream.py
> +        def __init__(self, source: t.Union[t.Iterable, t.Callable]):
passing `None` should be fine right?

2022-07-12 11:44 UTC, pzdkn commented on squirrel/iterstream/base.py
> +            assert inspect.signature(constructor).parameters["source"].default is None
Not sure if ValueError is the right Exception here

2022-07-12 12:34 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    class Add4(Composable):
this should fail

2022-07-12 13:05 UTC, AlirezaSohofi requested changes
LG, please also update the documentation.

2022-07-12 13:05 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
>              raise ValueError(f"source argument in {constructor} should be omitted")
```suggestion
            raise ValueError(f"If the class provides as constructor argument has an __init__ method, it should not have the source argument.")
```

2022-07-13 08:25 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        Compose the items in the stream with items generated by `constructor.
```suggestion
        Apply the transformation expressed in the `__iter__` method of the `constructor` to items in the stream.
```

2022-07-14 08:10 UTC, closed without merging