`SquirrelStore` should not fail if `clean=True` but store doesnt exist (nothing at URL)
merantix-momentum/squirrel-core pull request #72
Opened 2022-07-29 08:49 UTC by pzdkn

# Description

if clean==True -➝ it should remove the store if something exists, otherwise it should not fails but create the uri 
if clean==False -➝ url that exists: normal, url does not exists: it should not fails but create the uri 

Fixes # issue

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-07-29 09:34 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +def test_non_existent_path() -> None:
I recommend using the `test_path` fixture here (defined in `squirrel.integration_test.shared_fixtures`). It makes sure we try both local and GCS paths. You can check out the `test_catalog_saveandload` test for an example.

Note that `test_path` is a `str` and might contain filesystem protocol, so cannot use pathlib operations on it, would need to append the path like `f"{test_path}/non_existing"`.

It would be nice to also test the behavior when we want to create a store in an *existing* path, for completeness.

2022-07-29 13:38 UTC, AlirezaSohofi requested changes

2022-07-29 13:38 UTC, AlirezaSohofi commented on test/test_driver/test_sq_store.py
> +    temp_path_1 = pl.Path.cwd() / "tmp" / "non_existent_path_1"
please test `gs` paths too.

2022-07-29 14:01 UTC, pzdkn commented on test/test_driver/test_sq_store.py
> +    temp_path_1 = pl.Path.cwd() / "tmp" / "non_existent_path_1"
@AlirezaSohofi , what is the expected behaviour for gcs path though? Afaik, we can't create a folder structure there.

2022-07-29 15:07 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +    temp_path_1 = pl.Path.cwd() / "tmp" / "non_existent_path_1"
After writing at least one shard, the behavior should be the same for both filesystems. When writing a file (say, at `/path/dir/file`), fsspec adds some metadata to "folder" paths (/path and /path/dir) and later on it can infer that there is a directory at these paths.

So, we can write a shard in the test and then do the very same test for local and gcs filesystems (via the `test_path` fixture I mentioned above)

2022-08-03 07:10 UTC, pzdkn commented on test/test_driver/test_sq_store.py
> +    temp_path_1 = pl.Path.cwd() / "tmp" / "non_existent_path_1"
Hm but we want the directories to be created when the Store is initialized not manually beforehand by writing to the store, right @AlpAribal ?

2022-08-04 09:54 UTC, AlirezaSohofi requested changes
Looks good, just a minor comment to address.

2022-08-04 09:54 UTC, AlirezaSohofi commented on squirrel/store/squirrel_store.py
> +            self.fs.makedirs(self.url, exist_ok=True)
```suggestion
        self._create_dir_if_does_not_exists():
```

2022-08-04 09:54 UTC, AlirezaSohofi commented on squirrel/store/squirrel_store.py
> +            self.fs.makedirs(self.url, exist_ok=True)
Please introduce `self._dir_created = False` and avoid calling `self.fs.exists` for every set operation

2022-08-04 12:59 UTC, AlpAribal requested changes
Thanks for aligning different filesystems! Ali's comment makes a lot of sense, `fs.exists()` calls might add up if the store is huge

2022-08-04 12:59 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +    store = SquirrelStore(url=test_path, serializer=MessagepackSerializer(), clean=clean)
In case we change how we implement `test_path`, e.g. we return an existing path.

After importing
```
from squirrel.fsspec.fs import get_fs_from_url
```

```suggestion
    fs = get_fs_from_url(path)
    assert not fs.exists(test_path)
    store = SquirrelStore(url=test_path, serializer=MessagepackSerializer(), clean=clean)
```

2022-08-04 12:59 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +        assert len(FilePathGenerator(url=tmpdir).collect()) == 0
:rocket:

2022-08-05 08:29 UTC, AlpAribal requested changes

2022-08-05 08:29 UTC, AlpAribal commented on squirrel/store/filesystem.py
>              self.fs.rm(self.url, recursive=True)
At this point, the dir does not exist anymore, so we should set `self._dir_exists=False`. This bug can be validated by adding a `store.set(...)` at the end of the newly-added store creation tests.

2022-08-05 08:29 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +
Let's also try writing to the store here

2022-08-05 08:29 UTC, AlpAribal commented on test/test_driver/test_sq_store.py
> +    assert list(store.keys()) == []
Let's also try writing to the store here

2022-08-05 11:08 UTC, pzdkn commented on squirrel/store/filesystem.py
>              self.fs.rm(self.url, recursive=True)
How about when someone passes a non-empty directory at initialisation ?

2022-08-05 12:19 UTC, pzdkn commented on squirrel/store/filesystem.py
>              self.fs.rm(self.url, recursive=True)
that's a good catch, thanks!

2022-08-09 09:04 UTC, AlpAribal submitted a review, later dismissed
LGTM! Please make at least a minor version bump since we remove a public method.

2022-08-11 12:32 UTC, AlirezaSohofi submitted a review, later dismissed
LG :+1:

2022-08-12 06:16 UTC, AlpAribal approved these changes
LGTM, thank you for the meticulous work!

2022-08-12 09:52 UTC, pzdkn commented
Thanks for the great tips!

2022-08-12 09:53 UTC, merged