Throw error when creating driver that points to an empty directory
merantix-momentum/squirrel-core pull request #77
Opened 2022-08-04 10:15 UTC by pzdkn

# Description
An error is thrown when a driver is initialised with an invalid url. An invalid url can be a url that does not exists or points to an empty directory. 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-08-04 10:49 UTC, AlirezaSohofi requested changes

2022-08-04 10:49 UTC, AlirezaSohofi commented on squirrel/fsspec/fs.py
> +        raise ValueError(f"Path {url} is an empty directory")
we should only [warn](https://docs.python.org/3/library/warnings.html#warnings.warn) the user, not to raise an exception.

2022-08-04 10:49 UTC, AlirezaSohofi commented on squirrel/driver/store_driver.py
> +        validate_path(url)
The warning should be generated when the user tries to read from a store that is empty. It's a normal use case where the user instantiates a driver that points out to an empty or non-existing uri, with the intend to write to it.

2022-08-04 13:02 UTC, AlpAribal commented on squirrel/driver/store_driver.py
> +        validate_path(url)
Drivers are not able to write by definition, shall we align on this?

2022-08-04 14:01 UTC, AlirezaSohofi commented on squirrel/driver/store_driver.py
> +        validate_path(url)
This has been so far recommended, but not enforced. Having the property `store` in the driver implied that you can use driver api to instantiate something that can write. If we enforce this, we should remove the `store` property too imo.

2022-08-05 12:58 UTC, AlirezaSohofi requested changes

2022-08-05 12:58 UTC, AlirezaSohofi commented on squirrel/fsspec/fs.py
> +    if fs.isdir(url) and len(fs.find(url)) == 0:
`fs.find` will try to list all the files, this adds an unacceptable overhead to the majority of cases. 

`fs.isdir` does not work for gcs if the data is not written by gcsfs (@AlpAribal  correct me if I am wrong).

I think it not possible to avoid overhead if this is supposed to handle general cases. Since it is only used in `SquirrelStore`, which is always a flat directory of files, we don't need to consider nested directory structures.

2022-08-05 12:58 UTC, AlirezaSohofi commented on squirrel/fsspec/fs.py
> +    if fs.isdir(url) and len(fs.find(url)) == 0:
I suggest to move the validation to `FilePathGenerator` instead of the driver. Some advantages:

- it is used by many different drivers and even without drivers, so it's more widely useful
- we won't add any overhead

If FPG does not yields any item, then we can warn the user.

2022-08-05 12:58 UTC, AlirezaSohofi commented on test/test_driver/test_msgpack.py
> +    with tempfile.TemporaryDirectory() as tmp_dir:
what should happen if the directory does not exists?

2022-08-05 12:58 UTC, AlirezaSohofi commented on squirrel/fsspec/fs.py
> +def validate_path(url: str) -> None:
more descriptive name please

2022-08-09 09:08 UTC, AlpAribal commented
Shall we base this branch onto #72, there are some common changes in both, it might be safer to see how the changes combined work together.

2022-08-09 12:21 UTC, AlpAribal commented on squirrel/fsspec/fs.py
> +    if fs.isdir(url) and len(fs.find(url)) == 0:
> `fs.find` will try to list all the files, this adds an unacceptable overhead to the majority of cases.

Correct :+1: 

> `fs.isdir` does not work for gcs if the data is not written by gcsfs (@AlpAribal correct me if I am wrong).

That is also correct :+1: 
 
> I suggest to move the validation to FilePathGenerator instead of the driver.

We can maybe use [more_itertools.peekable()](https://more-itertools.readthedocs.io/en/latest/api.html#more_itertools.peekable) to check if the iterable is empty or not.

2022-08-09 12:23 UTC, AlpAribal commented on test/test_driver/test_msgpack.py
> +    with tempfile.TemporaryDirectory() as tmp_dir:
This is handles in #72, I really think we should merge these two PRs

2022-08-09 12:32 UTC, AlirezaSohofi commented
> Shall we base this branch onto #72, there are some common changes in both, it might be safer to see how the changes combined work together.

agree, can you please rebase this branch please @pzdkn?

2022-08-10 12:57 UTC, pzdkn commented
I have rebased and tests for both branches pass

2022-08-16 06:46 UTC, AlpAribal requested changes

2022-08-16 06:46 UTC, AlpAribal commented on squirrel/iterstream/source.py
> +                    self._returned_url = True
We need the same check for the `nested` case as well. I think, right now, we will get an empty warning for a dir containing only dirs but no files

2022-08-16 06:46 UTC, AlpAribal commented on test/test_driver/test_msgpack.py
> +                _ = MessagepackDriver(url=tmp_dir).get_iter().collect()
Why do we catch/filter warnings here?

2022-08-16 06:46 UTC, AlpAribal commented on test/test_driver/test_msgpack.py
> +        warnings.simplefilter("ignore")
Why do we catch/filter warnings here?

2022-08-16 06:46 UTC, AlpAribal commented on test/test_driver/test_msgpack.py
> +def test_invalid_url(local_msgpack_url: URL) -> None:
Would rename this test, it does not only use invalid urls.

2022-08-16 06:46 UTC, AlpAribal commented on test/test_driver/test_msgpack.py
> +def test_invalid_url(local_msgpack_url: URL) -> None:
We need to add `nested` cases here, perhaps via `parametrize`

2022-08-16 16:22 UTC, pzdkn commented on squirrel/iterstream/source.py
> +                    self._returned_url = True
Do we want to cover the nested case though? We are not reading in a nested way in the first place.

2022-08-16 16:24 UTC, pzdkn commented on test/test_driver/test_msgpack.py
> +                _ = MessagepackDriver(url=tmp_dir).get_iter().collect()
This is to check that when there are items in the store, then no warnings shall be printed. 
This `.simplefilter` asserts that no warning is shown:

https://stackoverflow.com/questions/45671803/how-to-use-pytest-to-assert-no-warning-is-raised

2022-08-16 16:27 UTC, pzdkn commented on test/test_driver/test_msgpack.py
> +                _ = MessagepackDriver(url=tmp_dir).get_iter().collect()
But it is in fact unintuitive, since a directory containing empty directories will no yield warnings

2022-08-17 13:06 UTC, AlirezaSohofi commented on squirrel/iterstream/source.py
> +                    self._returned_url = True
FilePathGenerator is not only menat to be used in `SquirrelStore`, so it should be general and and able to handle nested cases too.

2022-08-17 16:36 UTC, AlirezaSohofi commented on squirrel/iterstream/source.py
> +                                yield f"{self.protocol}{url}"
```suggestion
                            yield f"{self.protocol}{url}"
```

2022-08-23 15:35 UTC, AlirezaSohofi requested changes

2022-08-23 15:35 UTC, AlirezaSohofi commented on squirrel/iterstream/source.py
> +                    self._returned_file_url = True
```suggestion
                if not self._returned_file_url:
                    self._returned_file_url = True

```

2022-08-23 15:35 UTC, AlirezaSohofi commented on squirrel/iterstream/source.py
> +                    self._returned_file_url = True
why do we need ` not self.fs.isdir(path=url)`?

2022-09-07 13:13 UTC, closed without merging