Quantify randomness of shuffle in squirrel
merantix-momentum/squirrel-core pull request #86
Opened 2022-09-02 16:01 UTC by winfried-ripken

# Description

Introduce a function to measure the randomness of a shuffle operation in the squirrel pipeline by implementing a simple example driver, random sampling and comparing the distances of sampled trajectories.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-09-02 16:01 UTC, winfried-ripken commented
I have read the CLA Document and I hereby sign the CLA

2022-09-02 16:07 UTC, winfried-ripken commented
recheck

2022-10-05 09:18 UTC, AlirezaSohofi requested changes
Well done, the implementation looks good. I think it does not really belong to the `driver` module, we can add a new module `benchmark`. 

Please also add this to the documentation.

2022-10-05 09:18 UTC, AlirezaSohofi commented on test/test_driver/test_quantify_randomness.py
> +    assert ktau_deterministic > ktau_quasi_random > ktau_fully_random
please add assertion for upper and lower bounds

2022-10-05 09:18 UTC, AlirezaSohofi commented on test/test_driver/test_quantify_randomness.py
> +    ktau_deterministic = quantify_randomness(shards, shard_size, 1, 1)
maybe the default `250` samples is not really needed for test. wdyt?

2022-10-11 16:15 UTC, AlirezaSohofi commented on docs/advanced/randomness.rst
> +if the iid assumption holds approximately while we sample the data.
```suggestion
if the iid assumption holds approximately while we sample the data.
On the other hand, bigger shard size improves the loading performance
 substantially. Therefore we should aim for the biggest shard size that 
 does not hurt the approximate iid assumption. 
```

2022-10-11 16:16 UTC, AlirezaSohofi approved these changes
LGTM :+1:

2022-10-12 11:45 UTC, AlirezaSohofi commented
@winfried-ripken Please don't forget to re-base and bump the version

2022-10-19 10:49 UTC, merged