Peng add kwargs to map
merantix-momentum/squirrel-core pull request #90
Opened 2022-09-19 14:57 UTC by pzdkn

# Description

Currently to pass additional arguments to a mapped function, one needs wrap the function into `functools.partial`. This is not straightforward, and not very convenient. We instead wrap the kwargs inside the `map`, `async_map` and `dask_map`

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-09-20 08:28 UTC, AlirezaSohofi requested changes
LG, just some minor comments :+1:

2022-09-20 08:28 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
```suggestion
    def map(self, callback: t.Callable, *arg, **kw) -> _Iterable:
        """Applies the `callback` to each item in the stream"""
        partial_callback = partial(callback, *arg, **kw)
```

2022-09-20 08:28 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
same should be possible for other similar methods

2022-09-20 08:28 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    res_3 = IterableSource(res_2).map(multiply, factor=2).collect()
please add test the case where we only receive `*args`, or only `**kwargs`, or both.

2022-09-20 08:28 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    res_3 = IterableSource(res_2).map(multiply, factor=2).collect()
please also add the test for the case that the callback is `partial` and `*arg` and `**kwargs` are also provided by the user

2022-09-20 08:28 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        **kw,
please add this to the docstring and explain how this is used

2022-09-20 09:36 UTC, axkoenig requested changes
thanks good work! please see comments, afterwards lgtm

2022-09-20 09:36 UTC, axkoenig commented on docs/advanced/iterstream.rst
> +    * When a very complex  stream processing is needed that is hard to achieve with standard methods.
```suggestion
    * When a very complex stream processing is needed that is hard to achieve with standard methods.
```

2022-09-20 09:36 UTC, axkoenig commented on docs/usage/iterstream.rst
> +To pass additional arguments to the mapped function, simply pass them as additional key-word arguments.
```suggestion
To pass additional arguments to the mapped function, simply pass them as additional key-word arguments to `map`. This works analogously for `async_map` and `dask_map`.
```

2022-09-20 09:36 UTC, axkoenig commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
agreed. note that in our codebase we mostly use `**kwargs` and not `**kw`. I would suggest to keep this consistent and use `**kwargs` here. 
below are the only two instances of `**kw`, I think this could be a good opportunity to change them to `**kwargs`. 

<img width="733" alt="Screen Shot 2022-09-20 at 11 21 34" src="https://user-images.githubusercontent.com/50868646/191220330-bfee90f9-47e4-4077-bea7-5ce715588a9f.png">

2022-09-20 09:36 UTC, axkoenig commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
please explain each argument briefly in a docstring that has the same format as the one in e.g. `async_map`

2022-09-20 09:36 UTC, axkoenig commented on squirrel/iterstream/base.py
>          """Converts each item in the stream into a dask.delayed object by applying the callback to the item"""
please explain each argument briefly in a docstring that has the same format as the one in e.g. `async_map`

2022-09-20 09:36 UTC, axkoenig commented on squirrel/iterstream/base.py
>          """Converts each item in the stream into a dask.delayed object by applying the callback to the item"""
also, please add `*args` here

2022-09-20 09:36 UTC, axkoenig commented on test/test_iterstream/test_stream.py
>  def test_dask(samples: t.List[SampleType]) -> None:
I would expect `test_dask` to test `dask_map`. but you're testing `async_map` here. would also test `dask_map` (with args and kwargs) here or do that at in the function `test_different_maps` where `dask_map` is already tested

2022-09-20 11:56 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
adding `*args` might encourage some errors. For example you have 

```
def divide(value, divisor):
        return value / divisor
```
Then for,

`IterableSource(range(1, 3)).map(divide,  2)`

I personally would expect [1/2, 3/2], but gives you [2/1,  2/2]

2022-09-20 12:31 UTC, pzdkn commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
@AlirezaSohofi @axkoenig, wdyt ?

2022-09-21 08:16 UTC, AlirezaSohofi commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
@pzdkn Yes you are right, very good catch. I think there is a way to circumvent this but that probably requires refactoring of some of the internal machineries which is out of the scope for this pr. I'd suggest to just add `**kwargs` for now and tackle that in another pr.

2022-09-21 08:30 UTC, axkoenig commented on squirrel/iterstream/base.py
> +        partial_callback = partial(callback, **kw)
sounds good let's just go for `**kwargs` then :)

2022-09-21 09:41 UTC, axkoenig approved these changes
fine now thanks. only a minor docs update - I think these things are important to improve the docs quality of squirrel. also I would prefer `kwargs` instead of the `kw` which we typically don't use in squirrel - see my comment :)

2022-09-21 09:41 UTC, axkoenig commented on squirrel/iterstream/base.py
> +            **kw: key-word arguments for callback
You docstrings don't adhere to the official google docstring style that we're using in squirrel. e.g. you're not adding the type of the argument after the argument name. Same holds for the return statement. you would write `_Iterable: the mapped Squirrel iterable` or sth like that. 
I recommend to simply install a plugin in your IDE that formats this and gives you a skeleton in which you can fill it.

2022-09-21 11:18 UTC, pzdkn commented on squirrel/iterstream/base.py
> +            **kw: key-word arguments for callback
thanks for the hint!

2022-09-21 11:35 UTC, AlirezaSohofi submitted a review, later dismissed
LGTM :+1:

2022-09-21 11:35 UTC, AlirezaSohofi commented on test/test_iterstream/test_stream.py
> +    assert all(i == 21 for i in res_4)
minor: it would be easier to check the correctness of the logic if the input is e.g. `list(range(5))` and the assert statement compare the exact list than we expect to see rather than the sum `[1, 2, 3] == [3, ..., ....]`

2022-09-22 07:46 UTC, pzdkn commented on test/test_iterstream/test_stream.py
> +    assert all(i == 21 for i in res_4)
Just fixed this and need another review @AlirezaSohofi

2022-09-22 08:21 UTC, AlirezaSohofi approved these changes

2022-09-22 08:59 UTC, merged