Introducing DataFrameFileDriver
merantix-momentum/squirrel-core pull request #98
Opened 2022-10-21 14:23 UTC by MaxSchambach

# Description

Refactors all DataFrame related drivers. 
In particular:

- Fixes a current bug (I believe) that storage options are not passed down when reading using the pandas/dask interface. This affected the implementation of CsvDriver.
- Adds a new DataFrameFileDriver base class to provide a common interface for all drivers that use some read functionality from pandas or dask. The base class now handles the storage options and read arguments precedence for all derived classes
- Using the new abstraction, adds `JsonDriver`, `ParquetDriver`, and `XlsDriver`
- This does break some datasets using the CsvDriver as the `read_csv_kwargs` are now renamed to a common `read_kwargs`. However, so far, only two research datasets used this property. See the [corresponding PR in squirrel-datasets](https://github.com/merantix-momentum/squirrel-datasets/pull/95).
So far, this is a bit of a rough sketch. I tested the existing CsvDriver-based datasets but otherwise, this requires a bit more cleanup I suppose.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

2022-10-28 08:07 UTC, ThomasWollmann commented
Feather would be nice to support

2022-10-31 10:54 UTC, MaxSchambach commented
> Feather would be nice to support

Done. However, supporting Dask would require an additional `dask-geopandas` dependency, as Dask does not support feather by default, see [here](https://dask-geopandas.readthedocs.io/en/stable/docs/reference/api/dask_geopandas.read_feather.html).

Not sure, if an additional dependency is desired.

2022-11-02 15:28 UTC, winfried-ripken approved these changes
LG!
We need rebase and bump the version again before merging

2022-11-04 09:31 UTC, AlirezaSohofi commented
>

2022-11-04 09:34 UTC, AlirezaSohofi commented
> Done. However, supporting Dask would require an additional `dask-geopandas` dependency, as Dask does not support feather by default, see [this issue](https://github.com/dask/dask/issues/6865) and [the docs](https://dask-geopandas.readthedocs.io/en/stable/docs/reference/api/dask_geopandas.read_feather.html).
> 
> Not sure, if an additional dependency is desired.

Optional dependencies should go into `requirements.xxx.in`, similar to e.g. `requirements.zarr.in`. This would give our users more options without unnecessarily increase the dependencies.

2022-11-04 09:53 UTC, MaxSchambach commented
> Optional dependencies should go into `requirements.xxx.in`, similar to e.g. `requirements.zarr.in`. This would give our users more options without unnecessarily increase the dependencies.

Ok. However, I just tried installing `dask-geopandas` locally and it comes again with a lot of dependencies which don't all automatically resolve. So for me, a simple installation failed. It is based on `geopandas` which has quite a elaborate [installation guide](https://geopandas.org/en/stable/getting_started/install.html#installing-with-pip).

So I think there are more pitfalls in supporting dask feather reading while it only gives minor improvements and most people will already be happy with the pandas case that is already provided.

2022-11-04 13:29 UTC, AlirezaSohofi requested changes
Thanks a lot for the PR :+1: 

I think the requirements for new packages should be introduced before merging, and new drivers should have tests. I added some suggestion which are mostly minor and up to you to decide about.

2022-11-04 15:07 UTC, MaxSchambach commented on squirrel/driver/json_driver.py
> +from __future__ import annotations
Agreed, it was kind of a mixed convention so far. I've renamed all drivers in this module now, not only the once originally affected by this PR

2022-11-04 15:14 UTC, MaxSchambach commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
Agreed, it's not nice. We could get rid of the `DataFrameDriver` completely as it only defines the `get_df` functionality and is not used anywhere else, so it could be completely absorbed by the new `DataFrameFileDriver`.
Wdyt @AlirezaSohofi ?

2022-11-04 15:18 UTC, MaxSchambach commented on squirrel/driver/data_frame_file_driver.py
> +        **kwargs,
Done :)

2022-11-04 17:08 UTC, MaxSchambach commented on squirrel/driver/xls_driver.py
> +        return pd.read_excel(self.path, **kwargs)
Having a `requirements.excel.in` definitly makes sense, but I disagree that we should include all. The default suggestion to install squirrel is still using `[all]` so this would kind of blow up the installation. If people want to use another enginge, they would need to read the pandas doc anyway to find the `engine` option of `read_excel` which includes notes on which packages contain which engine. So they can easily install them when required.

So I would prefer to include only the default engine in our `requirements.excel.in`.

2022-11-04 17:10 UTC, AlirezaSohofi commented on squirrel/driver/xls_driver.py
> +        return pd.read_excel(self.path, **kwargs)
:+1:

2022-11-04 17:12 UTC, MaxSchambach commented on squirrel/driver/xls_driver.py
> +        return pd.read_excel(self.path, **kwargs)
Done 👍

2022-11-04 17:27 UTC, AlirezaSohofi commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
Makes sense to me.
Why do we call it `DataFrameFileDriver` and not `DataFrameDriver`? The child classes of this class expect different inds of `path` argument, e.g. for `CsvDriver` it's `my/path/to/file.csv`, but for parquet it can be a directory instead of a file. Not saying it's a problem, just a bit confused about the naming.

2022-11-04 17:31 UTC, AlirezaSohofi commented on squirrel/driver/json.py
> +class JsonDriver(DataFrameFileDriver):
`JsonDriver` should inherit from `FileDriver` not `DataFrameFileDriver`

2022-11-04 17:44 UTC, MaxSchambach commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
Yes, would agree to name it `DataFrameDriver` then.

Regarding the `path` argument: yes. Do you mean w.r.t. annotation or docstrings? Or actually both :D Not sure how to do this nicely in a generic way actually, without type annotating every derived driver separately according to the specific read functionality. But I think that would be the cleanest solution? The annotation in the parent class could then simply be `Any` which would actually trickle down to the `FileDriver`.

I guess another would be to define a `PathLike` annotation type collecting all the used ones. What do you prefer?

2022-11-04 17:50 UTC, AlirezaSohofi commented on squirrel/driver/xls.py
> +    name = "xls"
would suggest to rename it to something like `excel` to be generic, this may give the impression that only `xls` file formats are supported

2022-11-04 17:51 UTC, MaxSchambach commented on squirrel/driver/xls.py
> +    name = "xls"
Agreed, had the same thought also :)

2022-11-04 17:54 UTC, MaxSchambach commented on squirrel/driver/json.py
> +class JsonDriver(DataFrameFileDriver):
Not sure why? `JsonDriver` is conceptually the same as `CsvDriver` or `ExcelDriver` and uses Pandas or Dask to lead a `DataFrame` and thus makes use of the `get_df` and `read` functionality of `DataFrameDriver` (prvsly. `DataFrameFileDriver`).

2022-11-04 17:55 UTC, AlirezaSohofi commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
the type is `str`, so annotation is not an issue. Maybe we can call it `url`, to be the same as MessagepackDriver. The docstring should make this point explicit, and probably in each sub-class a description of what this argument can be (a file, a directory, or both)

2022-11-04 17:58 UTC, MaxSchambach commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
Mh, actually the type can be `str` as well as `Path` or even a file handle in most cases, and something more peculiar like `ExcelFile` or `xlrd.Book` in a specific case. I guess ducktyping sometimes is actually handy haha.

I would prefer `path` over `url` in most cases actually as it seems more generic to me. But either way, I agree that the docstring needs to reflect this. Will think about it and update accordingly.

2022-11-07 17:51 UTC, MaxSchambach commented on squirrel/driver/json.py
> +class JsonDriver(DataFrameFileDriver):
I've cleared up the docstring to clarify that this is about loading json DataFrames. For arbitrary Json file loading, FileDriver can be used.

2022-11-07 17:53 UTC, MaxSchambach commented on squirrel/driver/data_frame_file_driver.py
> +class DataFrameFileDriver(FileDriver, DataFrameDriver, metaclass=ABCMeta):
I've changed it to `url` throughout. However, there are still a lot of classes/methods, e.g. in `Catalog` that use path, maybe that's for another PR to straighten out. 

I've extended the docstrings to clarify on the URL types for which I added Pandas to the `intersphinx` plugin mappings.

2022-11-09 14:23 UTC, AlirezaSohofi commented
@winfried-ripken Can you please assess if the breaking changes mentioned in the PR description are significant or not?

2022-11-09 14:54 UTC, MaxSchambach commented on squirrel/driver/jsonl.py
> +from squirrel.driver.store import StoreDriver
So far, I can't any other places, e.g. also in `squirrel-datasets-core` that import it directly, so I would opt for changing it now as it likely does not break things.
But I also wanted to mention that it also regards `file_driver`

2022-11-09 15:00 UTC, MaxSchambach commented on test/test_driver/test_data_frame.py
> +    return name, path, dict(pandas=read_kwargs_pandas, dask=read_kwargs_dask)
Yes, it's using pytest's `tmp_path` [fixture](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html) that provides and tears down a temporary directory.

2022-11-09 15:08 UTC, MaxSchambach commented on squirrel/driver/json.py
> +class JsonDriver(DataFrameDriver):
Yes, I understand what you mean. 

I am a little hesitent to rename it to `JsonDataFrameDriver` as then it would also make sense to rename `CsvDataFrameDriver`, `FeatherDataFrameDriver`, etc. to be consistent which, however, is too verbose in my opinion.

So I guess the real question is: do we need a `JsonDriver` and if so, what do people load with it? Is loading a DataFrame from json really a use case? Or do people just want to load it.
If loading a DataFrame really is a use case, then I would opt to leave the naming as is.
If it is not a use-case, I would opt for actually removing `JsonDriver` entirely as people can just use the generic `FileDriver` to load a json file (not DataFrame) instead.

@winfried-ripken @AlirezaSohofi what do you think?

2022-11-09 16:34 UTC, AlirezaSohofi commented on squirrel/driver/json.py
> +class JsonDriver(DataFrameDriver):
If there is no immediate need I'd say we should not implement it.

2022-11-10 12:27 UTC, winfried-ripken approved these changes
Thanks for tagging @AlirezaSohofi 
I think the changes are non-breaking from sq-ds side.
There is still a test for the json driver which you removed earlier?
Otherwise all looks good to me :)

2022-11-10 12:29 UTC, MaxSchambach commented
Ups, yes, forgot about the `JsonDriver` test. Removed it. Thank you!

2022-11-10 13:50 UTC, AlirezaSohofi approved these changes
LG, thanks a lot for the amazing addition :+1:

2022-11-10 14:09 UTC, MaxSchambach commented
Thanks for the review and the discussion!

2022-11-10 14:10 UTC, merged